package utils;

public enum TokenType {
	IDENTYFIER, NUMBER, ASSIGNMENT, REL_OP, SUM, SUBTRACTION, MULTIPLICATION, DIVISION, LEFT_PARENTHESIS, 
	RIGHT_PARENTHESIS, KEYWORD, COLON, SEMICOLON, CADEIA, COMMA;
}
